### ISSUE TITLE
Add strategy to exclude certain entities

### ISSUE THREAD

**Issue by Spea** [Spea/fixture-dumper#12]
Sometimes it might be useful to exclude certain entities from generating a fixture file, so some sort of strategy to do this might be a good idea.

**Comment by ibasaw** [comment]
i try to implement this. When i launch the dumper, i got a segmentation fault, but no errors...don't know how to see what is caused this. I dump a DB with 12k lines max. I use FosuserBundle and sonata Media Bundle.

**Comment by Spea** [comment]
A segmentation fault is always tricky. It might have to do something with php itself, but then again it could be caused by a very big call stack. I will try to create a test with 12k rows and see if I get something similar.

**Comment by ibasaw** [comment]
found it with xdebug, my entity which extends FosUserBundle didn't have some getters...dumper gone into loop and crash. I can exclude entity but for now, this is 'hardcoded'. Look at my forks.
